# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-01-19 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebdjango', '0003_auto_20180117_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='proficiencies',
            field=models.CharField(default='[]', max_length=1000),
        ),
    ]
